name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: E2E Test
      run: npm run test:e2e
      env:
        CI: true
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        MYSQL_HOST: 127.0.0.1
        MYSQL_USER: root
        MYSQL_PASSWORD: password
        MYSQL_PORT: 3306
        MYSQL_DB: test
        DATABASE_URL: mysql://root:password@localhost:3306/tweet_app

